// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAt2ykBWp-QWtXhNbS0xp60EVtZyDR0ms',
    appId: '1:400109225742:web:2e233434ae7f799ff6f95f',
    messagingSenderId: '400109225742',
    projectId: 'fir-20bfa',
    authDomain: 'fir-20bfa.firebaseapp.com',
    storageBucket: 'fir-20bfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhgMIopDfT7wpFAiuRIl0XzSL09e28Xxs',
    appId: '1:400109225742:android:d21a86cd6ed3de4ff6f95f',
    messagingSenderId: '400109225742',
    projectId: 'fir-20bfa',
    storageBucket: 'fir-20bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkSEbUg-2DABUT8dBcLcczqD5jW_IZOy4',
    appId: '1:400109225742:ios:47888beaf161105bf6f95f',
    messagingSenderId: '400109225742',
    projectId: 'fir-20bfa',
    storageBucket: 'fir-20bfa.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkSEbUg-2DABUT8dBcLcczqD5jW_IZOy4',
    appId: '1:400109225742:ios:47888beaf161105bf6f95f',
    messagingSenderId: '400109225742',
    projectId: 'fir-20bfa',
    storageBucket: 'fir-20bfa.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAt2ykBWp-QWtXhNbS0xp60EVtZyDR0ms',
    appId: '1:400109225742:web:36eee6ef40ab266ff6f95f',
    messagingSenderId: '400109225742',
    projectId: 'fir-20bfa',
    authDomain: 'fir-20bfa.firebaseapp.com',
    storageBucket: 'fir-20bfa.firebasestorage.app',
  );
}
